version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/rails_tdd
    ports:
      - "3001:3001"
    environment:
      HUB_URL: http://chrome:4444/wd/hub
    depends_on:
      - db
      - chrome

  chrome:
    image: selenium/standalone-chrome:3.141.59-zirconium
    volumes:
      - /dev/shm:/dev/shm
  
volumes:
  db_data: